// ============================================================================
// PRODUCT PRIVACY POLICY DATA
// ============================================================================

export interface PrivacySection {
    title: string;
    content: { subtitle: string; text: string }[];
}

export interface ProductPrivacyPolicy {
    slug: string;
    productName: string;
    lastUpdated: string;
    intro: string;
    sections: PrivacySection[];
}

export const productPrivacyPolicies: ProductPrivacyPolicy[] = [
    {
        slug: "chimegenius-ai-pro",
        productName: "ChimeGenius AI Pro",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use ChimeGenius AI Pro, our AI-powered smart comment and reply generator. This Privacy Policy explains how we collect, use, disclose, and safeguard information when you use the ChimeGenius browser extension, interact with our platform, or generate AI-powered comments and replies across social media platforms.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "When you create a ChimeGenius AI Pro account, we collect your name, email address, and billing information. If you sign up using Google or a social media provider, we receive basic profile information from that provider (name and email)." },
                    { subtitle: "Social Media Post Context", text: "When you use ChimeGenius to generate a comment or reply, we temporarily process the text content, hashtags, and metadata of the social media post you are interacting with. This data is used solely for the purpose of generating a contextually relevant comment and is not permanently stored on our servers." },
                    { subtitle: "Generated Comments", text: "Comments and replies generated by our AI are transiently processed in memory during your session. We do not permanently store, log, or archive the text of generated comments unless you explicitly save them to your account's favorites or history feature." },
                    { subtitle: "Tone & Style Preferences", text: "Your selected tone presets (e.g., Professional, Funny, Bold) and any custom tone configurations you create are stored in your account to maintain personalized settings across sessions." },
                    { subtitle: "Usage Data", text: "We collect anonymized usage analytics including feature usage frequency, generation counts, tone selections, and session duration. We also collect technical data such as browser type, extension version, device type, and IP address for security and debugging purposes." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Comment Generation", text: "To process the context of social media posts and generate relevant, tone-appropriate comments and replies. All AI processing happens in real-time; post content is not retained after the generation request is fulfilled." },
                    { subtitle: "Personalization", text: "To maintain your tone presets, custom styles, and preferences across sessions. Your settings are synced securely to your account so they are available on any device." },
                    { subtitle: "Service Improvement", text: "Anonymized and aggregated usage patterns (e.g., which tones are most popular, average generation length) may be used to improve our AI models and user experience. Your individual comments or post context are never used for model training without explicit consent." },
                    { subtitle: "Communication", text: "To send essential service notifications, product updates, and security alerts. Marketing communications are sent only with your consent and you can opt out at any time." },
                    { subtitle: "Security & Abuse Prevention", text: "To detect and prevent misuse, spam generation, and abuse of our AI services. To enforce our Terms of Service and comply with platform policies." },
                ],
            },
            {
                title: "3. Browser Extension Data Handling",
                content: [
                    { subtitle: "Minimal Permissions", text: "ChimeGenius AI Pro requests only the minimum browser permissions necessary to operate — specifically, access to active tab content when you click on a comment box. We do not access your browsing history, bookmarks, or other browser data." },
                    { subtitle: "On-Page Processing", text: "The extension detects comment boxes on supported social media platforms and injects the ChimeGenius toolbar only when you click on a comment input field. No data is collected passively while you browse." },
                    { subtitle: "Data Transmission", text: "When you request a comment generation, only the relevant post context (text and metadata) is transmitted securely (TLS 1.3) to our API for processing. The response is delivered directly to your browser and inserted into the comment box." },
                    { subtitle: "No Background Activity", text: "The extension does not run background processes, track your browsing activity, or transmit data when you are not actively using the comment generation feature." },
                ],
            },
            {
                title: "4. Data Storage & Security",
                content: [
                    { subtitle: "Encryption", text: "All data transmitted between the browser extension and our servers is encrypted with TLS 1.3. Account data is encrypted at rest using AES-256." },
                    { subtitle: "Ephemeral Processing", text: "Social media post context sent for comment generation is processed in volatile memory and discarded immediately after the AI response is generated. No post content is written to persistent storage." },
                    { subtitle: "Infrastructure", text: "ChimeGenius AI Pro runs on secure cloud infrastructure with SOC 2 Type II compliance. We use isolated processing environments to ensure tenant data separation." },
                    { subtitle: "Access Controls", text: "Strict role-based access controls govern our internal systems. All production access is logged, audited, and limited to authorized engineering personnel." },
                ],
            },
            {
                title: "5. Data Sharing & Third Parties",
                content: [
                    { subtitle: "AI Providers", text: "We use OpenAI and Anthropic (Claude) APIs for natural language processing. Post context sent to these providers for comment generation is subject to our enterprise data processing agreements, which prohibit the use of your data for model training." },
                    { subtitle: "Social Media Platforms", text: "ChimeGenius AI Pro operates as a browser extension that interacts with social media platforms (LinkedIn, Instagram, Facebook, X, YouTube, Reddit). We comply with each platform's API terms and policies. We do not access platform APIs on your behalf — the extension works by interfacing with the platform's web interface in your browser." },
                    { subtitle: "Subprocessors", text: "We use trusted subprocessors including Vercel (hosting), Stripe (payments), and Resend (transactional email). Each subprocessor is bound by data protection agreements." },
                    { subtitle: "No Selling of Data", text: "We never sell, rent, or trade your personal information, social media data, or generated content to any third party for marketing or any other purpose." },
                ],
            },
            {
                title: "6. Data Retention",
                content: [
                    { subtitle: "Post Context Data", text: "Social media post context is processed transiently and discarded immediately after comment generation. No post content is retained." },
                    { subtitle: "Generated Comments", text: "Generated comments are not stored by default. If you opt into the comment history feature, your saved comments are retained for 90 days and then automatically deleted, unless you choose to keep them." },
                    { subtitle: "Account Data", text: "Account information and preferences are retained for the duration of your subscription plus 30 days after cancellation. Billing records are retained for 6 years for legal compliance." },
                    { subtitle: "Deletion Requests", text: "You can request complete deletion of your account and all associated data at any time by contacting our support team or through your account settings. Deletion is processed within 30 days." },
                ],
            },
            {
                title: "7. Your Rights",
                content: [
                    { subtitle: "", text: "Depending on your jurisdiction, you may have the right to: access, correct, or delete your personal data; export your data in a portable format; restrict or object to certain processing; withdraw consent for marketing communications; request information about automated decision-making. To exercise these rights, contact us at contact@cinuteinfomedia.com." },
                ],
            },
            {
                title: "8. Children's Privacy",
                content: [
                    { subtitle: "", text: "ChimeGenius AI Pro is not intended for use by individuals under the age of 18. We do not knowingly collect personal information from minors. If we become aware that we have collected data from a child, we will take steps to delete that information promptly." },
                ],
            },
            {
                title: "9. Changes to This Policy",
                content: [
                    { subtitle: "", text: "We may update this Privacy Policy to reflect changes in our practices, technology, or legal requirements. Material changes will be communicated via email or in-app notification. Continued use of ChimeGenius AI Pro after changes constitutes acceptance of the revised policy." },
                ],
            },
            {
                title: "10. Contact Information",
                content: [
                    { subtitle: "", text: "Privacy Team — Cinute InfoMedia\nEmail: contact@cinuteinfomedia.com\nPhone: +91-9004988859 / +91-7700995410\nAddress: Office #3, 2nd Floor, Ashley Tower, Kanakia Road, Vagad Nagar, Beverly Park, Mira Road, Mira Bhayandar, Mumbai, Maharashtra 401107, India." },
                ],
            },
        ],
    },
    {
        slug: "testriq-qa",
        productName: "TestriqQA",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use TestriqQA, our AI-powered QA and testing automation platform. This Privacy Policy explains how we collect, use, disclose, and safeguard information when you use TestriqQA or interact with its services.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "When you create a TestriqQA account, we collect your name, email address, company name, and billing information. If you sign up using a third-party provider (e.g., GitHub, GitLab), we receive basic profile information from that provider." },
                    { subtitle: "Repository & Code Data", text: "TestriqQA connects to your code repositories to generate and run tests. We access repository metadata, file structures, and code content as needed to provide our services. We do not store your source code permanently — it is processed in memory and discarded after analysis." },
                    { subtitle: "Test Results & Analytics", text: "We collect test execution logs, coverage reports, performance metrics, and error data generated during testing sessions. This data is used to display dashboards and improve AI test generation accuracy." },
                    { subtitle: "Usage Data", text: "We automatically collect information about how you interact with TestriqQA, including features used, test configurations, session duration, IP address, browser type, and device information." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Service Delivery", text: "To provide, maintain, and improve TestriqQA's AI test generation, visual regression testing, parallel execution, and reporting features." },
                    { subtitle: "AI Model Improvement", text: "Anonymized and aggregated test patterns may be used to improve our AI test generation models. Your proprietary code is never used for training without explicit consent." },
                    { subtitle: "Communication", text: "To send service-related notifications, product updates, security alerts, and billing information. Marketing communications are sent only with your consent." },
                    { subtitle: "Security & Compliance", text: "To detect and prevent fraud, abuse, and security incidents. To comply with legal obligations and enforce our terms of service." },
                ],
            },
            {
                title: "3. Data Storage & Security",
                content: [
                    { subtitle: "Infrastructure", text: "TestriqQA runs on AWS infrastructure with data centers in the US and EU. All data is encrypted at rest (AES-256) and in transit (TLS 1.3)." },
                    { subtitle: "Access Controls", text: "We implement strict role-based access controls. Only authorized personnel can access production systems, and all access is logged and audited." },
                    { subtitle: "SOC 2 Compliance", text: "TestriqQA maintains SOC 2 Type II compliance. We undergo annual third-party security audits and penetration testing." },
                    { subtitle: "Data Isolation", text: "Each customer's test data is logically isolated. CI/CD credentials and repository tokens are stored in encrypted vaults with automatic rotation." },
                ],
            },
            {
                title: "4. Data Sharing & Third Parties",
                content: [
                    { subtitle: "CI/CD Integrations", text: "When you connect TestriqQA to GitHub Actions, GitLab CI, Jenkins, or other CI/CD platforms, we exchange data necessary to trigger and report test results. We only access what is needed for the integration." },
                    { subtitle: "Subprocessors", text: "We use trusted subprocessors including AWS (hosting), Stripe (payments), SendGrid (email), and Sentry (error tracking). Each subprocessor is contractually bound to data protection obligations." },
                    { subtitle: "No Selling of Data", text: "We never sell, rent, or trade your personal information or code data to third parties for marketing purposes." },
                ],
            },
            {
                title: "5. Data Retention",
                content: [
                    { subtitle: "Test Results", text: "Test execution results and analytics are retained for 12 months by default. Enterprise customers can configure custom retention periods." },
                    { subtitle: "Account Data", text: "Account information is retained for the duration of your subscription plus 30 days after cancellation. Billing records are retained for 6 years for legal compliance." },
                    { subtitle: "Deletion Requests", text: "You can request deletion of your data at any time by contacting our support team. We will process deletion requests within 30 days." },
                ],
            },
            {
                title: "6. Your Rights",
                content: [
                    { subtitle: "", text: "Depending on your jurisdiction, you may have the right to: access, correct, or delete your personal data; export your data in a portable format; restrict or object to certain processing; withdraw consent for marketing communications. To exercise these rights, contact us at contact@cinuteinfomedia.com." },
                ],
            },
            {
                title: "7. Contact Information",
                content: [
                    { subtitle: "", text: "Privacy Team — Cinute InfoMedia\nEmail: contact@cinuteinfomedia.com\nPhone: +91-9004988859 / +91-7700995410\nAddress: Office #3, 2nd Floor, Ashley Tower, Kanakia Road, Vagad Nagar, Beverly Park, Mira Road, Mira Bhayandar, Mumbai, Maharashtra 401107, India." },
                ],
            },
        ],
    },
    {
        slug: "cim-chatbot",
        productName: "CIM ChatBot",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use CIM ChatBot, our AI-powered conversational platform. This Privacy Policy explains how we handle data collected through chatbot interactions, knowledge base uploads, and platform usage.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "Name, email, company name, and billing details provided during registration." },
                    { subtitle: "Knowledge Base Data", text: "Documents, FAQs, and website content you upload to train your chatbot. This data is processed and indexed for retrieval-augmented generation (RAG)." },
                    { subtitle: "Conversation Data", text: "Messages exchanged between your chatbot and end-users, including text content, timestamps, and session identifiers. This data powers analytics and chatbot improvement." },
                    { subtitle: "End-User Data", text: "Information provided by visitors interacting with your chatbot, such as names, email addresses, and phone numbers collected through lead qualification flows." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Chatbot Operation", text: "To process and respond to conversations using your knowledge base. RAG queries are processed in real-time and responses are generated based on your uploaded content." },
                    { subtitle: "Analytics & Improvement", text: "To generate conversation analytics, satisfaction scores, and performance metrics. Anonymized conversation patterns may be used to improve our NLP models." },
                    { subtitle: "Multi-Channel Delivery", text: "To deploy and manage your chatbot across website widget, WhatsApp, Messenger, Instagram, Slack, and Telegram. Each channel integration requires specific data handling per platform policies." },
                    { subtitle: "Lead Management", text: "To qualify, score, and route leads captured by your chatbot to your CRM or sales team via configured integrations." },
                ],
            },
            {
                title: "3. Data Storage & Security",
                content: [
                    { subtitle: "Encryption", text: "All conversation data is encrypted at rest (AES-256) and in transit (TLS 1.3). Knowledge base vectors are stored in isolated Pinecone namespaces." },
                    { subtitle: "Data Isolation", text: "Each customer's chatbot data, knowledge base, and conversation history are logically isolated. No cross-tenant data access is possible." },
                    { subtitle: "PII Handling", text: "End-user PII collected through chatbot interactions is stored securely and can be configured for automatic redaction or anonymization." },
                ],
            },
            {
                title: "4. Data Sharing & Integrations",
                content: [
                    { subtitle: "CRM Integrations", text: "When connected to HubSpot, Salesforce, or Zoho, lead data is transmitted to your CRM account. We act as a data processor in these scenarios." },
                    { subtitle: "Messaging Platforms", text: "Conversations on WhatsApp, Messenger, and other platforms are subject to those platforms' privacy policies in addition to ours." },
                    { subtitle: "AI Providers", text: "We use OpenAI APIs for natural language processing. Conversation data sent to OpenAI is not used for model training per our enterprise agreement." },
                ],
            },
            {
                title: "5. Data Retention & Deletion",
                content: [
                    { subtitle: "", text: "Conversation logs are retained for 6 months by default (configurable). Knowledge base data is retained for the duration of your subscription. You can delete individual conversations, entire knowledge bases, or request full account deletion at any time." },
                ],
            },
            {
                title: "6. Your Rights & Contact",
                content: [
                    { subtitle: "", text: "You have the right to access, correct, delete, or export your data. End-users can request data deletion through your chatbot's privacy controls. Contact us at contact@cinuteinfomedia.com for any privacy-related inquiries." },
                ],
            },
        ],
    },
    {
        slug: "cim-autoflow",
        productName: "CIM AutoFlow",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use CIM AutoFlow, our AI workflow automation engine. This Privacy Policy explains how we handle data processed through automated workflows, connected integrations, and platform usage.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "Name, email, company name, and billing details provided during registration." },
                    { subtitle: "Integration Credentials", text: "OAuth tokens and API keys for connected services (Salesforce, HubSpot, Google Workspace, etc.). These are encrypted and stored in isolated credential vaults." },
                    { subtitle: "Workflow Data", text: "Data processed through your automation workflows, including emails, form submissions, CRM records, documents, and any other data flowing through your pipelines." },
                    { subtitle: "Execution Logs", text: "Workflow execution history, step-by-step logs, error reports, and performance metrics." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Workflow Execution", text: "To execute your configured automation workflows, process triggers, apply conditional logic, and deliver outputs to connected services." },
                    { subtitle: "AI Decision Engine", text: "When AI-powered decision nodes are used, data is processed through our ML models to make routing decisions. Data is processed in real-time and not stored for model training." },
                    { subtitle: "Document Processing", text: "OCR and AI extraction services process documents in memory. Extracted data is sent to your configured destinations. Original documents are not retained beyond processing." },
                    { subtitle: "Analytics", text: "To generate execution analytics, success rates, and performance reports. Data is aggregated and anonymized for platform-wide improvements." },
                ],
            },
            {
                title: "3. Data Storage & Security",
                content: [
                    { subtitle: "Credential Security", text: "All OAuth tokens and API keys are stored in AES-256 encrypted vaults with automatic key rotation. Credentials are never logged or exposed in execution logs." },
                    { subtitle: "Data in Transit", text: "All data flowing through workflows is encrypted with TLS 1.3. Internal service communication uses mTLS (mutual TLS)." },
                    { subtitle: "Compliance", text: "CIM AutoFlow is SOC 2 Type II compliant and supports GDPR, CCPA, and HIPAA configurations for enterprise customers." },
                ],
            },
            {
                title: "4. Data Sharing & Integrations",
                content: [
                    { subtitle: "", text: "Data is shared only with services you explicitly connect to your workflows. We use Apache Kafka for internal event processing and AWS SQS for queue management. Subprocessors include AWS (hosting), Stripe (payments), and SendGrid (notifications). We never sell or share your workflow data with third parties." },
                ],
            },
            {
                title: "5. Data Retention & Deletion",
                content: [
                    { subtitle: "", text: "Execution logs are retained for 90 days by default (configurable up to 1 year). Workflow configurations are retained for the duration of your subscription. All data is deleted within 30 days of account cancellation." },
                ],
            },
            {
                title: "6. Your Rights & Contact",
                content: [
                    { subtitle: "", text: "You have the right to access, correct, delete, or export your data at any time. Contact us at contact@cinuteinfomedia.com for privacy inquiries.\n\nAddress: Office #3, 2nd Floor, Ashley Tower, Kanakia Road, Mira Road, Mumbai, Maharashtra 401107, India." },
                ],
            },
        ],
    },
    {
        slug: "cim-analytics",
        productName: "CIM Analytics",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use CIM Analytics, our marketing and SEO analytics dashboard. This Privacy Policy explains how we handle data collected from connected marketing platforms, analytics services, and platform usage.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "Name, email, company name, and billing details." },
                    { subtitle: "Connected Platform Data", text: "When you connect Google Analytics, Search Console, ad platforms, and social media accounts, we access read-only analytics data through OAuth. We do not modify your connected accounts." },
                    { subtitle: "Dashboard & Report Data", text: "Custom dashboard configurations, saved reports, alert settings, and annotation data created within CIM Analytics." },
                    { subtitle: "Client Portal Data", text: "If you use white-labeled client portals, we process client account details, access permissions, and branded report configurations." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Data Aggregation", text: "To unify marketing data from multiple sources into a single dashboard. Data is synced at regular intervals (15 minutes to 24 hours depending on the source)." },
                    { subtitle: "AI Insights", text: "To generate anomaly detection alerts, trend analysis, and optimization recommendations. AI processes aggregated data without accessing individual user records." },
                    { subtitle: "Report Generation", text: "To create scheduled PDF/CSV reports and deliver them to configured recipients." },
                ],
            },
            {
                title: "3. Data Storage & Security",
                content: [
                    { subtitle: "", text: "Analytics data is stored in ClickHouse databases with encryption at rest. OAuth tokens for connected platforms are stored in encrypted vaults. All data is processed in AWS data centers (US/EU). We maintain SOC 2 Type II compliance." },
                ],
            },
            {
                title: "4. Data Retention & Deletion",
                content: [
                    { subtitle: "", text: "Analytics data is retained for the duration of your subscription plus 30 days. Historical data beyond 24 months is automatically aggregated and anonymized. Full account deletion is available upon request." },
                ],
            },
            {
                title: "5. Your Rights & Contact",
                content: [
                    { subtitle: "", text: "You have the right to access, correct, delete, or export your data. Disconnect any connected platform at any time to stop data collection. Contact us at contact@cinuteinfomedia.com for privacy inquiries." },
                ],
            },
        ],
    },
    {
        slug: "cim-sitebuilder",
        productName: "CIM SiteBuilder",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use CIM SiteBuilder, our AI-powered website builder. This Privacy Policy explains how we handle data related to websites you build, content you create, and visitor data collected through your sites.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "Name, email, company name, and billing details." },
                    { subtitle: "Website Content", text: "Pages, images, text, configurations, and custom code you create within SiteBuilder. This content is stored to render and serve your websites." },
                    { subtitle: "Visitor Analytics", text: "If you enable our built-in analytics, we collect anonymized visitor data (page views, session duration, referral sources) for websites you build. No PII is collected from your visitors by default." },
                    { subtitle: "E-commerce Data", text: "If you use e-commerce features, customer orders, payment information (processed via Stripe/PayPal), and product data are collected as needed." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Website Hosting & Delivery", text: "To build, deploy, and serve your websites via our CDN infrastructure (Vercel/Cloudflare). Content is cached at edge locations globally for performance." },
                    { subtitle: "AI Design Assistant", text: "When you use AI design features, your prompts and selected preferences are processed to generate design suggestions. We do not store AI conversation history beyond the current session." },
                    { subtitle: "SEO Optimization", text: "To auto-generate meta tags, sitemaps, and schema markup for your websites." },
                ],
            },
            {
                title: "3. Data Storage & Security",
                content: [
                    { subtitle: "", text: "Website content is stored on Vercel/AWS infrastructure with automatic backups. All sites are served with free SSL certificates. E-commerce payment data is processed by Stripe/PayPal and never stored on our servers. We maintain SOC 2 compliance." },
                ],
            },
            {
                title: "4. Code Export & Portability",
                content: [
                    { subtitle: "", text: "You can export your website code (Next.js/React) at any time. Exported code is fully standalone with no vendor lock-in. Your content belongs to you — we claim no ownership rights." },
                ],
            },
            {
                title: "5. Your Rights & Contact",
                content: [
                    { subtitle: "", text: "You have full ownership of your website content and can export or delete it at any time. Contact us at contact@cinuteinfomedia.com for privacy inquiries." },
                ],
            },
        ],
    },
    {
        slug: "cim-socialhub",
        productName: "CIM SocialHub",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use CIM SocialHub, our social media management platform. This Privacy Policy explains how we handle data from connected social accounts, scheduled content, and analytics.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "Name, email, company name, and billing details." },
                    { subtitle: "Social Account Data", text: "When you connect social media accounts (Instagram, Facebook, LinkedIn, Twitter, TikTok, Pinterest, YouTube), we access account metadata, post history, and engagement metrics via official APIs. We request only the permissions necessary for scheduling and analytics." },
                    { subtitle: "Content Data", text: "Posts, images, videos, captions, hashtags, and scheduling configurations you create within SocialHub." },
                    { subtitle: "Inbox & Engagement Data", text: "If you use the unified inbox, we access DMs, comments, and mentions from connected platforms to display in your dashboard." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Content Publishing", text: "To schedule and publish posts to your connected social media accounts at configured times." },
                    { subtitle: "AI Content Creation", text: "When using AI content features, your prompts, brand voice settings, and selected preferences are processed to generate content suggestions. Generated content is stored in your account." },
                    { subtitle: "Analytics", text: "To aggregate engagement data, follower growth, and content performance metrics from connected platforms into unified dashboards." },
                    { subtitle: "Hashtag Research", text: "To analyze trending topics and suggest relevant hashtags based on aggregated, anonymized platform data." },
                ],
            },
            {
                title: "3. Social Platform Compliance",
                content: [
                    { subtitle: "", text: "CIM SocialHub complies with the API terms and data policies of all connected platforms (Meta Platform Policy, Twitter Developer Agreement, LinkedIn API Terms, TikTok API Terms). We only access data within the scope of granted permissions and never exceed authorized usage." },
                ],
            },
            {
                title: "4. Data Storage & Security",
                content: [
                    { subtitle: "", text: "Social account tokens are stored in encrypted vaults with automatic rotation. Content and analytics data are stored in PostgreSQL with encryption at rest. All data is processed in AWS data centers. We maintain SOC 2 Type II compliance." },
                ],
            },
            {
                title: "5. Data Retention & Deletion",
                content: [
                    { subtitle: "", text: "Scheduled content is retained indefinitely unless deleted by you. Analytics data is retained for 24 months. Disconnecting a social account immediately revokes our API access. Full account deletion is processed within 30 days." },
                ],
            },
            {
                title: "6. Your Rights & Contact",
                content: [
                    { subtitle: "", text: "You have the right to access, correct, delete, or export your data. Disconnect any social account at any time. Contact us at contact@cinuteinfomedia.com for privacy inquiries." },
                ],
            },
        ],
    },
];

export function getProductPrivacyBySlug(slug: string): ProductPrivacyPolicy | undefined {
    return productPrivacyPolicies.find((p) => p.slug === slug);
}

