// ============================================================================
// PRODUCT PRIVACY POLICY DATA
// ============================================================================

export interface PrivacySection {
    title: string;
    content: { subtitle: string; text: string }[];
}

export interface ProductPrivacyPolicy {
    slug: string;
    productName: string;
    lastUpdated: string;
    intro: string;
    sections: PrivacySection[];
}

export const productPrivacyPolicies: ProductPrivacyPolicy[] = [
    {
        slug: "chimegenius-ai-pro",
        productName: "ChimeGenius AI Pro",
        lastUpdated: "May 16, 2026",
        intro: "At Cinute InfoMedia (\"CIM\", \"we\", \"us\"), we are committed to protecting your privacy when you use ChimeGenius AI Pro, our AI-powered smart comment and reply generator. This Privacy Policy explains how we collect, use, disclose, and safeguard information when you use the ChimeGenius browser extension, interact with our platform, or generate AI-powered comments and replies across social media platforms.",
        sections: [
            {
                title: "1. Information We Collect",
                content: [
                    { subtitle: "Account Information", text: "When you create a ChimeGenius AI Pro account, we collect your name, email address, and billing information. If you sign up using Google or a social media provider, we receive basic profile information from that provider (name and email)." },
                    { subtitle: "Social Media Post Context", text: "When you use ChimeGenius to generate a comment or reply, we temporarily process the text content, hashtags, and metadata of the social media post you are interacting with. This data is used solely for the purpose of generating a contextually relevant comment and is not permanently stored on our servers." },
                    { subtitle: "Generated Comments", text: "Comments and replies generated by our AI are transiently processed in memory during your session. We do not permanently store, log, or archive the text of generated comments unless you explicitly save them to your account's favorites or history feature." },
                    { subtitle: "Tone & Style Preferences", text: "Your selected tone presets (e.g., Professional, Funny, Bold) and any custom tone configurations you create are stored in your account to maintain personalized settings across sessions." },
                    { subtitle: "Usage Data", text: "We collect anonymized usage analytics including feature usage frequency, generation counts, tone selections, and session duration. We also collect technical data such as browser type, extension version, device type, and IP address for security and debugging purposes." },
                ],
            },
            {
                title: "2. How We Use Your Information",
                content: [
                    { subtitle: "Comment Generation", text: "To process the context of social media posts and generate relevant, tone-appropriate comments and replies. All AI processing happens in real-time; post content is not retained after the generation request is fulfilled." },
                    { subtitle: "Personalization", text: "To maintain your tone presets, custom styles, and preferences across sessions. Your settings are synced securely to your account so they are available on any device." },
                    { subtitle: "Service Improvement", text: "Anonymized and aggregated usage patterns (e.g., which tones are most popular, average generation length) may be used to improve our AI models and user experience. Your individual comments or post context are never used for model training without explicit consent." },
                    { subtitle: "Communication", text: "To send essential service notifications, product updates, and security alerts. Marketing communications are sent only with your consent and you can opt out at any time." },
                    { subtitle: "Security & Abuse Prevention", text: "To detect and prevent misuse, spam generation, and abuse of our AI services. To enforce our Terms of Service and comply with platform policies." },
                ],
            },
            {
                title: "3. Browser Extension Data Handling",
                content: [
                    { subtitle: "Minimal Permissions", text: "ChimeGenius AI Pro requests only the minimum browser permissions necessary to operate — specifically, access to active tab content when you click on a comment box. We do not access your browsing history, bookmarks, or other browser data." },
                    { subtitle: "On-Page Processing", text: "The extension detects comment boxes on supported social media platforms and injects the ChimeGenius toolbar only when you click on a comment input field. No data is collected passively while you browse." },
                    { subtitle: "Data Transmission", text: "When you request a comment generation, only the relevant post context (text and metadata) is transmitted securely (TLS 1.3) to our API for processing. The response is delivered directly to your browser and inserted into the comment box." },
                    { subtitle: "No Background Activity", text: "The extension does not run background processes, track your browsing activity, or transmit data when you are not actively using the comment generation feature." },
                ],
            },
            {
                title: "4. Data Storage & Security",
                content: [
                    { subtitle: "Encryption", text: "All data transmitted between the browser extension and our servers is encrypted with TLS 1.3. Account data is encrypted at rest using AES-256." },
                    { subtitle: "Ephemeral Processing", text: "Social media post context sent for comment generation is processed in volatile memory and discarded immediately after the AI response is generated. No post content is written to persistent storage." },
                    { subtitle: "Infrastructure", text: "ChimeGenius AI Pro runs on secure cloud infrastructure with SOC 2 Type II compliance. We use isolated processing environments to ensure tenant data separation." },
                    { subtitle: "Access Controls", text: "Strict role-based access controls govern our internal systems. All production access is logged, audited, and limited to authorized engineering personnel." },
                ],
            },
            {
                title: "5. Data Sharing & Third Parties",
                content: [
                    { subtitle: "AI Providers", text: "We use OpenAI and Anthropic (Claude) APIs for natural language processing. Post context sent to these providers for comment generation is subject to our enterprise data processing agreements, which prohibit the use of your data for model training." },
                    { subtitle: "Social Media Platforms", text: "ChimeGenius AI Pro operates as a browser extension that interacts with social media platforms (LinkedIn, Instagram, Facebook, X, YouTube, Reddit). We comply with each platform's API terms and policies. We do not access platform APIs on your behalf — the extension works by interfacing with the platform's web interface in your browser." },
                    { subtitle: "Subprocessors", text: "We use trusted subprocessors including Vercel (hosting), Stripe (payments), and Resend (transactional email). Each subprocessor is bound by data protection agreements." },
                    { subtitle: "No Selling of Data", text: "We never sell, rent, or trade your personal information, social media data, or generated content to any third party for marketing or any other purpose." },
                ],
            },
            {
                title: "6. Data Retention",
                content: [
                    { subtitle: "Post Context Data", text: "Social media post context is processed transiently and discarded immediately after comment generation. No post content is retained." },
                    { subtitle: "Generated Comments", text: "Generated comments are not stored by default. If you opt into the comment history feature, your saved comments are retained for 90 days and then automatically deleted, unless you choose to keep them." },
                    { subtitle: "Account Data", text: "Account information and preferences are retained for the duration of your subscription plus 30 days after cancellation. Billing records are retained for 6 years for legal compliance." },
                    { subtitle: "Deletion Requests", text: "You can request complete deletion of your account and all associated data at any time by contacting our support team or through your account settings. Deletion is processed within 30 days." },
                ],
            },
            {
                title: "7. Your Rights",
                content: [
                    { subtitle: "", text: "Depending on your jurisdiction, you may have the right to: access, correct, or delete your personal data; export your data in a portable format; restrict or object to certain processing; withdraw consent for marketing communications; request information about automated decision-making. To exercise these rights, contact us at contact@cinuteinfomedia.com." },
                ],
            },
            {
                title: "8. Children's Privacy",
                content: [
                    { subtitle: "", text: "ChimeGenius AI Pro is not intended for use by individuals under the age of 18. We do not knowingly collect personal information from minors. If we become aware that we have collected data from a child, we will take steps to delete that information promptly." },
                ],
            },
            {
                title: "9. Changes to This Policy",
                content: [
                    { subtitle: "", text: "We may update this Privacy Policy to reflect changes in our practices, technology, or legal requirements. Material changes will be communicated via email or in-app notification. Continued use of ChimeGenius AI Pro after changes constitutes acceptance of the revised policy." },
                ],
            },
            {
                title: "10. Contact Information",
                content: [
                    { subtitle: "", text: "Privacy Team — Cinute InfoMedia\nEmail: contact@cinuteinfomedia.com\nPhone: +91-9004988859 / +91-7700995410\nAddress: Office #3, 2nd Floor, Ashley Tower, Kanakia Road, Vagad Nagar, Beverly Park, Mira Road, Mira Bhayandar, Mumbai, Maharashtra 401107, India." },
                ],
            },
        ],
    },
];

export function getProductPrivacyBySlug(slug: string): ProductPrivacyPolicy | undefined {
    return productPrivacyPolicies.find((p) => p.slug === slug);
}

